env:
  global: 
    - WORKSPACE="Specs.xcworkspace"

matrix:
  include:
    - os: linux
      language: generic
      dist: xenial
      env: SWIFT_VERSION="5.1-DEVELOPMENT-SNAPSHOT-2019-09-05-a"
      sudo: required
    - os: linux
      language: generic
      dist: xenial
      env: SWIFT_VERSION="5.0"
      sudo: required
    - os: osx
      language: swift
      osx_image: xcode10.3
      env:
        - SCHEME="CombineX"
        - SDK="iphonesimulator12.4"
        - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=12.4"
    - os: osx
      language: swift
      osx_image: xcode11
      env:
        - SCHEME="CombineX"
        - SDK="iphonesimulator13.0"
        - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=13.0"
    - os: osx
      language: swift
      osx_image: xcode11
      env:
        - SCHEME="Specs"
        - SDK="iphonesimulator13.0"
        - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=13.0"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      gem install xcpretty;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      eval "$(curl -sL https://raw.githubusercontent.com/kylef/swiftenv/master/docs/install.sh)";
    fi

script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      cd Specs;
      xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      swift test;
    fi
